meta_product_name: "Patrick Music"
meta_title: "Patrick Music - All of Patrick's Music"
meta_description: "A website that hosts Patrick's monthly, themed, and suggested playlists."
meta_image: "Patrick-Music-Logo.png"